import AnonMale from "./board-members-images/anonMale.png";
import AnnonFemale from "./board-members-images/anonFemale.png";

const ExecutiveBody2022 = [
  {
    fullName: "Md. Muhtadee Faiaz Khan Soumik",
    nickName: "Soumik",
    department: "Governing Body",
    designation: "President",
    image: AnonMale,
  },
  {
    fullName: "Md Ashikul Islam",
    nickName: "Ashikul",
    department: "Governing Body",
    designation: "Vice President",
    image: AnonMale,
  },
  {
    fullName: "Farah Jasmin Khan",
    nickName: "Farah",
    department: "Governing Body",
    designation: "General Secretary",
    image: AnnonFemale,
  },
  {
    fullName: "Ishrat Jahan Mitu",
    nickName: "Mitu",
    department: "Communication and Marketing",
    designation: "Director",
    image: AnnonFemale,
  },
  {
    fullName: "Fahmida Hridy",
    nickName: "Hridy",
    department: "Communication and Marketing",
    designation: "Director",
    image: AnnonFemale,
  },
  {
    fullName: "Arnab Saha Authro",
    nickName: "Arnab",
    department: "Communication and Marketing",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Maliha Bushra Hoque",
    nickName: "Maliha",
    department: "Creative",
    designation: "Director",
    image: AnnonFemale,
  },
  {
    fullName: "Mumtahinah Rahman Sristy",
    nickName: "Sristy",
    department: "Creative",
    designation: "Director",
    image: AnnonFemale,
  },
  {
    fullName: "Syed Zuhair Hossain",
    nickName: "Zuhair",
    department: "Creative",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Md. Sabbir Al Mamon",
    nickName: "Mamon",
    department: "Creative",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Sohanur Rahman",
    nickName: "Sohanur",
    department: "Creative",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Nazim Uddin",
    nickName: "Nazim",
    department: "Event Management",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Maliha Tabassum",
    nickName: "Maliha",
    department: "Event Management",
    designation: "Director",
    image: AnnonFemale,
  },
  {
    fullName: "Niamotullah Ratul",
    nickName: "Ratul",
    department: "Event Management",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Md. Nazrul Islam",
    nickName: "Nazrul",
    department: "Event Management",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Rahat Khan",
    nickName: "Rahat",
    department: "Event Management",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "G.M. Arafat Rahman",
    nickName: "Arafat",
    department: "Finance",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Sanjida Afroz Shefa",
    nickName: "Shefa",
    department: "Finance",
    designation: "Director",
    image: AnnonFemale,
  },
  {
    fullName: "Shishir Kumar Das",
    nickName: "Shishir",
    department: "Finance",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Maymuna Rukaiya",
    nickName: "Rukaiya",
    department: "Finance",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
  {
    fullName: "Shadab Iqbal",
    nickName: "Shadab",
    department: "Human Resources",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Ahnaf Ar Rasheed",
    nickName: "Ahnaf",
    department: "Human Resources",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Md. Zariful Huq",
    nickName: "Zariful",
    department: "Human Resources",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Sanjib Sen",
    nickName: "Sanjib",
    department: "Press Release and Publication",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Meshaq Monsur",
    nickName: "Meshaq",
    department: "Press Release and Publication",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Tonusree Talukder Trina",
    nickName: "Trina",
    department: "Press Release and Publication",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
];

export default ExecutiveBody2022;
