import AnonMale from "./board-members-images/anonMale.png";
import AnnonFemale from "./board-members-images/anonFemale.png";

const ExecutiveBody2021 = [
  {
    fullName: "Mahima Rabbi",
    nickName: "Mahima",
    department: "Governing Body",
    designation: "President",
    image: AnnonFemale,
  },
  {
    fullName: "Rawha Mikdad Chowdhury",
    nickName: "Rawha",
    department: "Governing Body",
    designation: "Vice President",
    image: AnonMale,
  },
  {
    fullName: "Dhruba Chakraborty",
    nickName: "Dhruba",
    department: "Governing Body",
    designation: "General Secretary",
    image: AnonMale,
  },
  {
    fullName: "Shanjida Habib Shormi",
    nickName: "Shormi",
    department: "Communication and Marketing",
    designation: "Director",
    image: AnnonFemale,
  },
  {
    fullName: "Abrar Shahriar Abeed",
    nickName: "Abeed",
    department: "Communication and Marketing",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Tanzimul Haque",
    nickName: "Tanzimul",
    department: "Creative",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Rubuyat Jahan Roshne",
    nickName: "Roshne",
    department: "Creative",
    designation: "Director",
    image: AnnonFemale,
  },
  {
    fullName: "Sakib Hassan Chowdhury",
    nickName: "Sakib",
    department: "Creative",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Sameha Kamrul",
    nickName: "Sameha",
    department: "Creative",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
  {
    fullName: "Saraf Noor Khaled",
    nickName: "Saraf",
    department: "Creative",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Ahnaf Rahman Khan",
    nickName: "Ahnaf",
    department: "Event Management",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Md. Ashikur Rahman",
    nickName: "Ashikur",
    department: "Event Management",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "MD. Sadman Sakib",
    nickName: "Sadman",
    department: "Event Management",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Md. Muntaha Islam",
    nickName: "Muntaha",
    department: "Event Management",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Abdullah All Faisal",
    nickName: "Faisal",
    department: "Event Management",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Md. Sabbir Ahmed Saimoon",
    nickName: "Saimoon",
    department: "Event Management",
    designation: "Senior Executive",
    image: AnonMale,
  },
  {
    fullName: "MD Humaion Kabir Mehedi",
    nickName: "Mehedi",
    department: "Event Management",
    designation: "Senior Executive",
    image: AnonMale,
  },
  {
    fullName: "Sourojit Roy",
    nickName: "Sourojit",
    department: "Finance",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Ishrak Rahman Shourav",
    nickName: "Shourav",
    department: "Finance",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "M Ragib Anjum Riad",
    nickName: "Riad",
    department: "Finance",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Rowshanara Sadia",
    nickName: "Sadia",
    department: "Human Resources",
    designation: "Director",
    image: AnnonFemale,
  },
  {
    fullName: "Sadia Rahman Mou",
    nickName: "Mou",
    department: "Human Resources",
    designation: "Director",
    image: AnnonFemale,
  },
  {
    fullName: "Faizun Nahar Faria",
    nickName: "Faria",
    department: "Human Resources",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
  {
    fullName: "Jannatul Ferdous",
    nickName: "Jannatul",
    department: "Press Release and Publication",
    designation: "Director",
    image: AnnonFemale,
  },
  {
    fullName: "Shabab Masiat",
    nickName: "Shabab",
    department: "Press Release and Publication",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Md.Abrar Ur Rahman",
    nickName: "Abrar",
    department: "Press Release and Publication",
    designation: "Assistant Director",
    image: AnonMale,
  },
];

export default ExecutiveBody2021;
