const blogCategories = [
  { id: 1, name: "Web Development", slug: "web-development" },
  { id: 2, name: "Mobile Development", slug: "mobile-development" },
  { id: 3, name: "Game Development", slug: "game-development" },
  { id: 4, name: "Data Science", slug: "data-science" },
  { id: 5, name: "Machine Learning", slug: "machine-learning" },
  { id: 6, name: "Artificial Intelligence", slug: "artificial-intelligence" },
  { id: 7, name: "Cloud Computing", slug: "cloud-computing" },
  { id: 8, name: "Blockchain", slug: "blockchain" },
  { id: 9, name: "Cybersecurity", slug: "cybersecurity" },
  { id: 10, name: "DevOps", slug: "devops" },
  { id: 11, name: "UI/UX Design", slug: "ui-ux-design" },
  { id: 12, name: "Augmented Reality", slug: "augmented-reality" },
  { id: 13, name: "Virtual Reality", slug: "virtual-reality" },
  { id: 14, name: "Internet of Things", slug: "internet-of-things" },
  { id: 15, name: "Programming Languages", slug: "programming-languages" },
  { id: 16, name: "Software Engineering", slug: "software-engineering" },
  { id: 17, name: "Open Source", slug: "open-source" },
  { id: 18, name: "Competitive Programming", slug: "competitive-programming" },
  { id: 19, name: "Tech Events", slug: "tech-events" },
  { id: 20, name: "Hackathons", slug: "hackathons" },
  { id: 21, name: "Career Development", slug: "career-development" },
  { id: 22, name: "Leadership", slug: "leadership" },
  { id: 23, name: "Networking", slug: "networking" },
  { id: 24, name: "Quantum Computing", slug: "quantum-computing" },
  { id: 25, name: "Big Data", slug: "big-data" },
  { id: 26, name: "Robotics", slug: "robotics" },
  { id: 27, name: "Startup Culture", slug: "startup-culture" },
  { id: 28, name: "Digital Marketing", slug: "digital-marketing" },
  { id: 29, name: "Education", slug: "education" },
  { id: 30, name: "Tech Reviews", slug: "tech-reviews" },
  { id: 31, name: "Productivity", slug: "productivity" },
  { id: 32, name: "Campus life", slug: "campus-life" },
  { id: 33, name: "Games", slug: "games" },
  { id: 34, name: "Entertainment", slug: "entertainment" },
  { id: 35, name: "Anime", slug: "anime" },
  { id: 36, name: "Psychology", slug: "psychology" },
];

const blogTags = [
  // Programming Languages
  { id: 1, name: "Python", slug: "python" },
  { id: 2, name: "JavaScript", slug: "javascript" },
  { id: 3, name: "TypeScript", slug: "typescript" },
  { id: 4, name: "Java", slug: "java" },
  { id: 5, name: "C++", slug: "cpp" },
  { id: 6, name: "C#", slug: "csharp" },
  { id: 7, name: "Go", slug: "go" },
  { id: 8, name: "Rust", slug: "rust" },
  { id: 9, name: "Kotlin", slug: "kotlin" },
  { id: 10, name: "Swift", slug: "swift" },
  { id: 11, name: "PHP", slug: "php" },
  { id: 12, name: "Ruby", slug: "ruby" },
  { id: 13, name: "R", slug: "r" },
  { id: 14, name: "MATLAB", slug: "matlab" },
  { id: 15, name: "Perl", slug: "perl" },
  { id: 16, name: "Scala", slug: "scala" },
  { id: 17, name: "Haskell", slug: "haskell" },
  { id: 18, name: "Lua", slug: "lua" },
  { id: 19, name: "Dart", slug: "dart" },
  { id: 20, name: "Shell", slug: "shell" },

  // Web Development
  { id: 21, name: "HTML", slug: "html" },
  { id: 22, name: "CSS", slug: "css" },
  { id: 23, name: "React", slug: "react" },
  { id: 24, name: "Next.js", slug: "nextjs" },
  { id: 25, name: "Node.js", slug: "nodejs" },
  { id: 26, name: "Angular", slug: "angular" },
  { id: 27, name: "Vue.js", slug: "vuejs" },
  { id: 28, name: "Svelte", slug: "svelte" },
  { id: 29, name: "Gatsby", slug: "gatsby" },
  { id: 30, name: "Tailwind CSS", slug: "tailwind-css" },
  { id: 31, name: "Bootstrap", slug: "bootstrap" },
  { id: 32, name: "Express.js", slug: "expressjs" },

  // Mobile Development
  { id: 33, name: "React Native", slug: "react-native" },
  { id: 34, name: "Flutter", slug: "flutter" },
  { id: 35, name: "SwiftUI", slug: "swiftui" },
  { id: 36, name: "Ionic", slug: "ionic" },
  { id: 37, name: "Xamarin", slug: "xamarin" },

  // Machine Learning & AI
  { id: 38, name: "Machine Learning", slug: "machine-learning" },
  { id: 39, name: "Deep Learning", slug: "deep-learning" },
  { id: 40, name: "Data Science", slug: "data-science" },
  { id: 41, name: "Artificial Intelligence", slug: "artificial-intelligence" },
  { id: 42, name: "Computer Vision", slug: "computer-vision" },
  { id: 43, name: "Natural Language Processing", slug: "nlp" },
  { id: 44, name: "TensorFlow", slug: "tensorflow" },
  { id: 45, name: "PyTorch", slug: "pytorch" },
  { id: 46, name: "Keras", slug: "keras" },

  // Databases
  { id: 47, name: "MySQL", slug: "mysql" },
  { id: 48, name: "PostgreSQL", slug: "postgresql" },
  { id: 49, name: "MongoDB", slug: "mongodb" },
  { id: 50, name: "SQLite", slug: "sqlite" },
  { id: 51, name: "Redis", slug: "redis" },
  { id: 52, name: "Firebase", slug: "firebase" },
  { id: 53, name: "Elasticsearch", slug: "elasticsearch" },
  { id: 54, name: "Cassandra", slug: "cassandra" },
  { id: 55, name: "MariaDB", slug: "mariadb" },

  // DevOps & Tools
  { id: 56, name: "Docker", slug: "docker" },
  { id: 57, name: "Kubernetes", slug: "kubernetes" },
  { id: 58, name: "Terraform", slug: "terraform" },
  { id: 59, name: "Ansible", slug: "ansible" },
  { id: 60, name: "Git", slug: "git" },
  { id: 61, name: "GitHub", slug: "github" },
  { id: 62, name: "GitLab", slug: "gitlab" },
  { id: 63, name: "Jenkins", slug: "jenkins" },
  { id: 64, name: "CircleCI", slug: "circleci" },
  { id: 65, name: "AWS", slug: "aws" },
  { id: 66, name: "Google Cloud", slug: "google-cloud" },
  { id: 67, name: "Azure", slug: "azure" },

  // Cybersecurity
  { id: 68, name: "Cybersecurity", slug: "cybersecurity" },
  { id: 69, name: "Ethical Hacking", slug: "ethical-hacking" },
  { id: 70, name: "Penetration Testing", slug: "penetration-testing" },
  { id: 71, name: "Cryptography", slug: "cryptography" },
  { id: 72, name: "Web Security", slug: "web-security" },

  // Miscellaneous
  { id: 73, name: "Blockchain", slug: "blockchain" },
  { id: 74, name: "IoT", slug: "iot" },
  { id: 75, name: "Quantum Computing", slug: "quantum-computing" },
  { id: 76, name: "Augmented Reality", slug: "augmented-reality" },
  { id: 77, name: "Virtual Reality", slug: "virtual-reality" },
  { id: 78, name: "Game Development", slug: "game-development" },
  { id: 79, name: "Open Source", slug: "open-source" },
  { id: 80, name: "Hackathons", slug: "hackathons" },
  { id: 81, name: "Coding Challenges", slug: "coding-challenges" },
  { id: 82, name: "UI/UX Design", slug: "ui-ux-design" },
  { id: 83, name: "Figma", slug: "figma" },
  { id: 84, name: "Adobe XD", slug: "adobe-xd" },
  { id: 85, name: "ChatGPT", slug: "chatgpt" },
  { id: 86, name: "Bard", slug: "bard" },

  // Competitive Programming
  { id: 87, name: "Competitive Programming", slug: "competitive-programming" },
  { id: 88, name: "LeetCode", slug: "leetcode" },
  { id: 89, name: "Codeforces", slug: "codeforces" },
  { id: 90, name: "HackerRank", slug: "hackerrank" },
  { id: 91, name: "CodeChef", slug: "codechef" },

  // Career & Personal Growth
  { id: 92, name: "Career Development", slug: "career-development" },
  { id: 93, name: "Leadership", slug: "leadership" },
  { id: 94, name: "Personal Growth", slug: "personal-growth" },
  { id: 95, name: "Teamwork", slug: "teamwork" },
  { id: 96, name: "Innovation", slug: "innovation" },

  // Events & Workshops
  { id: 97, name: "Events", slug: "events" },
  { id: 98, name: "Workshops", slug: "workshops" },
  { id: 99, name: "Conferences", slug: "conferences" },
  { id: 100, name: "Networking", slug: "networking" },
];

export { blogCategories, blogTags };
