const BUCCSEs = [
  {
    name: "Nafi Zawoad",
    studentId: "23101344",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Creative",
    personalEmail: "nafiartcell06@gmail.com",
    gSuiteEmail: "sardar.md.nafizawoad@g.bracu.ac.bd",
    contactNumber: "01736764637",
    emergencyContact: "01320753761",
    bloodGroup: "B+",
    birthDate: "2001-10-13",
    gender: "Male",
    joinedBracu: "Spring 2023",
    joinedBucc: "Spring 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/d3structor.wolf",
    LinkedIn: "https://www.facebook.com/d3structor.wolf",
    Github: null,
  },
  {
    name: "Humayra Anjum Nisha",
    studentId: "22101081",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Human Resources",
    personalEmail: "humayra.nisha03@gmail.com",
    gSuiteEmail: "humayra.anjum.nisha@g.bracu.ac.bd",
    contactNumber: "01740221859",
    emergencyContact: "01740221859",
    bloodGroup: "O+",
    birthDate: "2000-8-3",
    gender: "Female",
    joinedBracu: "Spring 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/humayra.anjum.9041",
    LinkedIn: "https://www.linkedin.com/in/humayra-anjum-nisha-b41a30218",
    Github: "https://github.com/HumayraAnjumNisha",
  },
  {
    name: "Farsin Rahman Nahin",
    studentId: "22101475",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Finance",
    personalEmail: "farsin.nahin@gmail.com",
    gSuiteEmail: "farsin.rahman.nahin@g.bracu.ac.bd",
    contactNumber: "01767902717",
    emergencyContact: "01637334646",
    bloodGroup: "AB+",
    birthDate: "2002-12-7",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/RahmanNahin.Farsin",
    LinkedIn: "https://www.linkedin.com/in/farsin-rahman-nahin-a25913227",
    Github: "https://github.com/far965",
  },
  {
    name: "Shahriar",
    studentId: "22201898",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Finance",
    personalEmail: "mn9447109@gmail.com",
    gSuiteEmail: "shahriar@g.bracu.ac.bd",
    contactNumber: "01788454513",
    emergencyContact: "01581808745",
    bloodGroup: "B+",
    birthDate: "2003-11-24",
    gender: "Male",
    joinedBracu: "Fall 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/nahid.shahriar.731",
    LinkedIn: "https://www.linkedin.com/in/shahriar-nahid-7019462a9",
    Github: null,
  },
  {
    name: "Mohtasim ahmed",
    studentId: "22301442",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Communications and Marketing",
    personalEmail: "mohtasimahmedsami@gmail.com",
    gSuiteEmail: "mohtasim.ahmed@g.bracu.ac.bd",
    contactNumber: "01883449196",
    emergencyContact: "01883449196",
    bloodGroup: "O+",
    birthDate: "2002-9-19",
    gender: "Male",
    joinedBracu: "Summer 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/mohtasimahmed.sami.1",
    LinkedIn: "https://www.linkedin.com/in/mohtasim-ahmed-0a634a277",
    Github: "https://github.com/Brownspite",
  },
  {
    name: "Ridwanur Rahman",
    studentId: "22301532",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Creative",
    personalEmail: "ridwanurrahman214@gmail.com",
    gSuiteEmail: "md.ridwanur.rahman@g.bracu.ac.bd",
    contactNumber: "01711322970",
    emergencyContact: "01905126681",
    bloodGroup: "B+",
    birthDate: "2002-5-8",
    gender: "Male",
    joinedBracu: "Summer 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/ridwan.rahman.2002",
    LinkedIn: "https://www.linkedin.com/in/ridwanur-rahman",
    Github: "https://github.com/Ridwan805",
  },
  {
    name: "Ishrat Jahan",
    studentId: "22201747",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "ishratj2001@gmail.com",
    gSuiteEmail: "ishrat.jahan7@g.bracu.ac.bd",
    contactNumber: "01708332060",
    emergencyContact: "01708332060",
    bloodGroup: "AB+",
    birthDate: "2001-8-28",
    gender: "Female",
    joinedBracu: "Fall 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/profile.php?id=100059935052227",
    LinkedIn: null,
    Github: null,
  },
  {
    name: "Sindid Arafat",
    studentId: "22299496",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Creative",
    personalEmail: "sindidarafat275@gmail.com",
    gSuiteEmail: "sindid.arafat@g.bracu.ac.bd",
    contactNumber: "01735807816",
    emergencyContact: "01735400068",
    bloodGroup: "AB+",
    birthDate: "2004-3-4",
    gender: "Male",
    joinedBracu: "Fall 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/sindidarafat.6",
    LinkedIn: null,
    Github: null,
  },
  {
    name: "Zaynul Abedin Miah",
    studentId: "22341034",
    departmentBracu: "CS",
    designation: "Senior Executive",
    buccDepartment: "Communications and Marketing",
    personalEmail: "azaynul3@gmail.com",
    gSuiteEmail: "zaynul.abedin.miah@g.bracu.ac.bd",
    contactNumber: "01620132606",
    emergencyContact: "01620132606",
    bloodGroup: "O+",
    birthDate: "2002-7-8",
    gender: "Male",
    joinedBracu: "Summer 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/zaynulabedin11",
    LinkedIn: "https://www.linkedin.com/in/zaynul-abedin-miah",
    Github: "https://github.com/azaynul10",
  },
  {
    name: "Syed Noor Arefin Farhan",
    studentId: "22101908",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Human Resources",
    personalEmail: "snarefin1@gmail.com",
    gSuiteEmail: "noor.arefin.farhan@g.bracu.ac.bd",
    contactNumber: "01908516177",
    emergencyContact: "01711142127",
    bloodGroup: "O+",
    birthDate: "2005-1-17",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/snarefin",
    LinkedIn: "https://www.linkedin.com/in/syed-noor-arefin-farhan-76b486258",
    Github: "https://github.com/SyedNoorArefin",
  },
  {
    name: "Md. Affan Hossain Rakib",
    studentId: "22201936",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Finance",
    personalEmail: "affanhossainrakib@gmail.com",
    gSuiteEmail: "affan.hossain.rakib@g.bracu.ac.bd",
    contactNumber: "01795204677",
    emergencyContact: "01521782438",
    bloodGroup: "A+",
    birthDate: "2003-11-24",
    gender: "Male",
    joinedBracu: "Fall 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/affanhossainrakib",
    LinkedIn: "https://www.linkedin.com/in/affanhossainrakib",
    Github: "https://github.com/AffanHossainRakib/",
  },
  {
    name: "Md. Abdullah Al Afeef",
    studentId: "22101784",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Creative",
    personalEmail: "coder.afeef@gmail.com",
    gSuiteEmail: "abdullah.al.afeef@g.bracu.ac.bd",
    contactNumber: "01712882660",
    emergencyContact: "01796655003",
    bloodGroup: "O+",
    birthDate: "2002-10-22",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/your.afeef",
    LinkedIn: "https://www.linkedin.com/in/your-afeef",
    Github: "https://github.com/Afeef001",
  },
  {
    name: "Oindrila Saha",
    studentId: "23341052",
    departmentBracu: "CS",
    designation: "Senior Executive",
    buccDepartment: "Communications and Marketing",
    personalEmail: "oindrilasaha45@gmail.com",
    gSuiteEmail: "oindrila.saha@g.bracu.ac.bd",
    contactNumber: "01744581005",
    emergencyContact: "01794567774",
    bloodGroup: "A+",
    birthDate: "2003-10-16",
    gender: "Female",
    joinedBracu: "Summer 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/Oindrila.Saha.Dia",
    LinkedIn: null,
    Github: null,
  },
  {
    name: "Sazzad Hossen Himel",
    studentId: "21301066",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Creative",
    personalEmail: "himel.s.hossain@gmail.com",
    gSuiteEmail: "sazzad.hossen.himel@g.bracu.ac.bd",
    contactNumber: "01626415005",
    emergencyContact: "01626415005",
    bloodGroup: "O+",
    birthDate: "2000-9-26",
    gender: "Male",
    joinedBracu: "Summer 2021",
    joinedBucc: "Fall 2021",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/himel.s.hossain",
    LinkedIn: "https://www.linkedin.com/in/sazzad-hossen-6205392a3",
    Github: "https://github.com/SazzadHimel",
  },
  {
    name: "Mehedi Hasan",
    studentId: "22201652",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Research and Development",
    personalEmail: "mehedi200.3.1@gmail.com",
    gSuiteEmail: "mehedi.hasan10@g.bracu.ac.bd",
    contactNumber: "01843852377",
    emergencyContact: "01814250125",
    bloodGroup: "A+",
    birthDate: "2001-11-25",
    gender: "Male",
    joinedBracu: "Fall 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/sakib8.12fff",
    LinkedIn: "https://www.linkedin.com/in/mehedi00hasan",
    Github: "https://github.com/Peru00",
  },
  {
    name: "Shafiur Rahman Rad",
    studentId: "22201909",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "shafiur008@gmail.com",
    gSuiteEmail: "shafiur.rahman.rad@g.bracu.ac.bd",
    contactNumber: "01309634127",
    emergencyContact: "01902998726",
    bloodGroup: "A+",
    birthDate: "2002-8-8",
    gender: "Male",
    joinedBracu: "Fall 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/profile.php?id=100072754745638",
    LinkedIn: "https://www.linkedin.com/in/shafiur-rahman-rad-879717290",
    Github: "https://github.com/Rad0130/Worker.git",
  },
  {
    name: "Rabsa Anjum Proshongsha",
    studentId: "22201112",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Press Release and Publications",
    personalEmail: "ra.proshongsha@gmail.com",
    gSuiteEmail: "rabsa.anjum.prosongsha@g.bracu.ac.bd",
    contactNumber: "01755103202",
    emergencyContact: "01775339805",
    bloodGroup: "AB+",
    birthDate: "2002-3-8",
    gender: "Female",
    joinedBracu: "Fall 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Spring 2024",
    Facebook: null,
    LinkedIn: "https://www.linkedin.com/in/rabsa-anjum-prosongsha-4b9300263",
    Github: null,
  },
  {
    name: "Tahmid Iqbal",
    studentId: "21201701",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Press Release and Publications",
    personalEmail: "md.tahmid.iqbal@g.bracu.ac.bd",
    gSuiteEmail: "md.tahmid.iqbal@g.bracu.ac.bd",
    contactNumber: "01773714424",
    emergencyContact: "01773714424",
    bloodGroup: "A+",
    birthDate: "2002-8-17",
    gender: "Male",
    joinedBracu: "Fall 2021",
    joinedBucc: "Spring 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/profile.php?id=100073382900528",
    LinkedIn: "https://www.linkedin.com/in/tahmid-iqbal-3ba355237",
    Github: "https://github.com/TahmidRaven",
  },
  {
    name: "M. ALIUL SIDDIQUE ANTOR",
    studentId: "21301633",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Press Release and Publications",
    personalEmail: "moliulsiddique@gmail.com",
    gSuiteEmail: "aliul.siddique.antor@g.bracu.ac.bd",
    contactNumber: "01775515812",
    emergencyContact: "01875928739",
    bloodGroup: "A+",
    birthDate: "2003-5-20",
    gender: "Male",
    joinedBracu: "Summer 2021",
    joinedBucc: "Summer 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/moliul.siddique",
    LinkedIn: "https://www.linkedin.com/in/m-aliul-siddique-antor",
    Github: "https://github.com/Antor1971",
  },
  {
    name: "Md. Sakib Khan",
    studentId: "22101054",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "zensakib@gmail.con",
    gSuiteEmail: "md.sakib.khan1@g.bracu.ac.bd",
    contactNumber: "01641956122",
    emergencyContact: "01941223083",
    bloodGroup: "B+",
    birthDate: "2002-6-15",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/sakeb.0",
    LinkedIn: "https://bd.linkedin.com/in/sakeb-khan-2b55b7285",
    Github: "https://github.com/zensakeb",
  },
  {
    name: "Mehedi Hasan Tanvir",
    studentId: "22101107",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Communications and Marketing",
    personalEmail: "mehedihtanvir@gmail.com",
    gSuiteEmail: "mehedi.hasan.tanvir1@g.bracu.ac.bd",
    contactNumber: "01643909454",
    emergencyContact: "01781871439",
    bloodGroup: "O+",
    birthDate: "2000-11-21",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/mhthe1",
    LinkedIn: "https://www.linkedin.com/in/mehedi-hasan-tanvir-5507b0228",
    Github: "https://github.com/MHThe1",
  },
  {
    name: "Md. Tariquzzaman",
    studentId: "22201581",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Human Resources",
    personalEmail: "tariquzzaman01@g.bracu.ac.bd",
    gSuiteEmail: "md.tariquzzaman@g.bracu.ac.bd",
    contactNumber: "01675309031",
    emergencyContact: "01779960988",
    bloodGroup: "B+",
    birthDate: "2002-10-1",
    gender: "Male",
    joinedBracu: "Fall 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/tariquzzaman01",
    LinkedIn: "https://www.linkedin.com/in/tariquzzaman01",
    Github: "https://github.com/Tariq-15",
  },
  {
    name: "Genius Rabbani",
    studentId: "22201924",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Communications and Marketing",
    personalEmail: "ge.rabbani@gmail.com",
    gSuiteEmail: "genius.rabbani@g.bracu.ac.bd",
    contactNumber: "01756660125",
    emergencyContact: "01517969209",
    bloodGroup: "A+",
    birthDate: "2003-9-17",
    gender: "Female",
    joinedBracu: "Fall 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/profile.php?id=100005578936338",
    LinkedIn: "https://www.linkedin.com/in/genius-rabbani-6219a630b",
    Github: null,
  },
  {
    name: "Angkon Dutta Joy",
    studentId: "22101024",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "angkondutta@gmail.com",
    gSuiteEmail: "angkon.dutta.joy@g.bracu.ac.bd",
    contactNumber: "01826133074",
    emergencyContact: "01826344765",
    bloodGroup: "O+",
    birthDate: "2002-10-26",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/Angkondutta",
    LinkedIn: "https://www.linkedin.com/in/angkon-dutta-joy-3a705425a",
    Github: "https://github.com/Angkon-Dutta-Joy",
  },
  {
    name: "MD HEMEL UDDIN CHOWDHURY",
    studentId: "22299367",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Communications and Marketing",
    personalEmail: "hemeluddin1612602930@gmail.com",
    gSuiteEmail: "hemel.uddin.chowdhury@g.bracu.ac.bd",
    contactNumber: "01739985924",
    emergencyContact: "01838777029",
    bloodGroup: "O+",
    birthDate: "2002-11-8",
    gender: "Male",
    joinedBracu: "Fall 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/hemel.ch0whdury",
    LinkedIn: "https://www.linkedin.com/in/md-hemel-uddin-chowdhury-95461b261",
    Github: "https://github.com/nasablueberry",
  },
  {
    name: "Yasir Arafat",
    studentId: "22101691",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Human Resources",
    personalEmail: "yasirarafat963369@gmail.com",
    gSuiteEmail: "yasir.arafat3@g.bracu.ac.bd",
    contactNumber: "01552397820",
    emergencyContact: "01623981477",
    bloodGroup: "O+",
    birthDate: "2002-12-8",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/yasirarafat9630",
    LinkedIn: "www.linkedin.com/in/yasir-arafat-99659225a",
    Github: "https://github.com/yasirarafat9633",
  },
  {
    name: "Tasnim Hamid Tisha",
    studentId: "24141151",
    departmentBracu: "CS",
    designation: "Senior Executive",
    buccDepartment: "Human Resources",
    personalEmail: "tasnimhamidtisha@gmail.com",
    gSuiteEmail: "tasnim.hamid.tisha@g.bracu.ac.bd",
    contactNumber: "01707734384",
    emergencyContact: "01708673447",
    bloodGroup: "AB+",
    birthDate: "2002-12-23",
    gender: "Female",
    joinedBracu: "Spring 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/profile.php?id=100015950258829",
    LinkedIn: "https://www.linkedin.com/in/tasnim-hamid-tisha-897b20282",
    Github: "https://github.com/TasnimTisha",
  },
  {
    name: "Jareen Tasneem Khondaker",
    studentId: "22301308",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Human Resources",
    personalEmail: "jareen.tasneem.khondaker@g.bracu.ac.bd",
    gSuiteEmail: "jareen.tasneem.khondaker@g.bracu.ac.bd",
    contactNumber: "01315647505",
    emergencyContact: "01581600280",
    bloodGroup: "O+",
    birthDate: "2003-7-13",
    gender: "Female",
    joinedBracu: "Summer 2022",
    joinedBucc: "Summer 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/jareentasneem713",
    LinkedIn: null,
    Github: "https://github.com/Jareen-Tasneem",
  },
  {
    name: "Arnab Saha",
    studentId: "22201299",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Finance",
    personalEmail: "aniksahacomilla0@gmail.com",
    gSuiteEmail: "arnab.saha1@g.bracu.ac.bd",
    contactNumber: "01995697724",
    emergencyContact: "01700866893",
    bloodGroup: "AB+",
    birthDate: "2003-12-14",
    gender: "Male",
    joinedBracu: "Fall 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/arnabsaha.anik",
    LinkedIn: null,
    Github: null,
  },
  {
    name: "Sadia Afrin",
    studentId: "22201490",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Creative",
    personalEmail: "afrinsadia2029@gmail.com",
    gSuiteEmail: "sadia.afrin17@g.bracu.ac.bd",
    contactNumber: "01710925277",
    emergencyContact: "01710925277",
    bloodGroup: "A+",
    birthDate: "2003-9-19",
    gender: "Female",
    joinedBracu: "Fall 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/profile.php?id=100073346444814",
    LinkedIn: null,
    Github: null,
  },
  {
    name: "Md. Jahidul Hasan",
    studentId: "22301146",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "captainjahid45@gmail.com",
    gSuiteEmail: "md.jahidul.hasan1@g.bracu.ac.bd",
    contactNumber: "01827832458",
    emergencyContact: "01827832458",
    bloodGroup: "A+",
    birthDate: "2001-7-20",
    gender: "Male",
    joinedBracu: "Summer 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/captain.jahid45",
    LinkedIn: "https://www.linkedin.com/in/mdjahid11",
    Github: "https://github.com/mrjahid11",
  },
  {
    name: "Md. Hasin Saleh Alvi",
    studentId: "24141161",
    departmentBracu: "CS",
    designation: "Senior Executive",
    buccDepartment: "Press Release and Publications",
    personalEmail: "hasinsaleh2015@gmail.com",
    gSuiteEmail: "hasin.saleh.alvi@g.bracu.ac.bd",
    contactNumber: "01722365044",
    emergencyContact: "01644370350",
    bloodGroup: "O+",
    birthDate: "2001-1-6",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/profile.php?id=100006029806492",
    LinkedIn: null,
    Github: "https://github.com/Hasinzz",
  },
  {
    name: "Amit Sutradhar",
    studentId: "22201054",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Creative",
    personalEmail: "amitsutradhar002@gmail.com",
    gSuiteEmail: "amit.sutradhar@g.bracu.ac.bd",
    contactNumber: "01810015492",
    emergencyContact: "01301010465",
    bloodGroup: "B+",
    birthDate: "2002-1-21",
    gender: "Male",
    joinedBracu: "Fall 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/amitshutradhar.amitshutradhar",
    LinkedIn: "https://www.linkedin.com/in/amitsutradhar002",
    Github: "https://github.com/amitsutradhar02",
  },
  {
    name: "Zinia Ahmed Toushy",
    studentId: "22101208",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "ziniat310@gmail.com",
    gSuiteEmail: "zinia.ahmed.toushy@g.bracu.ac.bd",
    contactNumber: "01756747800",
    emergencyContact: "01922868179",
    bloodGroup: "O+",
    birthDate: "2002-10-3",
    gender: "Female",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/profile.php?id=100069952542533",
    LinkedIn: "https://www.linkedin.com/in/zinia-ahmed-toushy-36a8b9228",
    Github: "https://github.com/Zinia-Ahmed-Toushy",
  },
  {
    name: "Mohini Khondoker",
    studentId: "22201784",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "khondokermohini4@gmail.com",
    gSuiteEmail: "mohini.khondoker@g.bracu.ac.bd",
    contactNumber: "01792282670",
    emergencyContact: "01749790657",
    bloodGroup: "O+",
    birthDate: "2003-10-17",
    gender: "Female",
    joinedBracu: "Fall 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/profile.php?id=100072433610361",
    LinkedIn: "https://www.linkedin.com/in/mohini-khondoker-246429299",
    Github: null,
  },
  {
    name: "a z m bodruddoza bijoy",
    studentId: "22301678",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "azmbodruddozabijoy@gmail.com",
    gSuiteEmail: "azm.bodruddoza.bijoy@g.bracu.ac.bd",
    contactNumber: "01648583672",
    emergencyContact: "01991436965",
    bloodGroup: "AB+",
    birthDate: "2003-10-12",
    gender: "Male",
    joinedBracu: "Summer 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/azm.bodruddozabijoy",
    LinkedIn: "https://www.linkedin.com/in/a-z-m-bodruddoza-bijoy-878409247",
    Github: "https://github.com/bijoy6965",
  },
  {
    name: "Agradip Saha",
    studentId: "22301188",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Finance",
    personalEmail: "sahaagradip10@gmail.com",
    gSuiteEmail: "agradip.saha@g.bracu.ac.bd",
    contactNumber: "01907930407",
    emergencyContact: "01734822515",
    bloodGroup: "B+",
    birthDate: "2003-12-12",
    gender: "Male",
    joinedBracu: "Summer 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/agradip10",
    LinkedIn: null,
    Github: null,
  },
  {
    name: "Mohammad Ridwanul Islam",
    studentId: "21201663",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "i.ridwanul22@gmail.com",
    gSuiteEmail: "mohammad.ridwanul.islam@g.bracu.ac.bd",
    contactNumber: "01745401176",
    emergencyContact: "01843679061",
    bloodGroup: "B+",
    birthDate: "2000-10-1",
    gender: "Male",
    joinedBracu: "Fall 2021",
    joinedBucc: "Spring 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/i.ridwanul22",
    LinkedIn: "https://www.linkedin.com/in/mohammad-ridwanul-islam",
    Github: null,
  },
  {
    name: "Anisha Irin Ahmed",
    studentId: "21201552",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Press Release and Publications",
    personalEmail: "anishairinahmed@gmail.com",
    gSuiteEmail: "anisha.irin.ahmed@g.bracu.ac.bd",
    contactNumber: "01960115664",
    emergencyContact: "01960115664",
    bloodGroup: "B+",
    birthDate: "2002-9-19",
    gender: "Female",
    joinedBracu: "Fall 2021",
    joinedBucc: "Spring 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/megha.ahmed.19",
    LinkedIn: "https://www.linkedin.com/in/anisha-irin-ahmed-84113a225",
    Github: null,
  },
  {
    name: "S N Prottasha",
    studentId: "22101775",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Communications and Marketing",
    personalEmail: "prottashasn99@gmail.com",
    gSuiteEmail: "sn.prottasha@g.bracu.ac.bd",
    contactNumber: "01767759804",
    emergencyContact: "01624998223",
    bloodGroup: "O+",
    birthDate: "2000-9-24",
    gender: "Female",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/sn.prottasha",
    LinkedIn: null,
    Github: null,
  },
  {
    name: "Tawsif Islam Chowdhury",
    studentId: "24341276",
    departmentBracu: "CS",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "chowdhurytawsifislam@gmail.com",
    gSuiteEmail: "tawsif.islam.chowdhury@g.bracu.ac.bd",
    contactNumber: "01639500138",
    emergencyContact: "01716849635",
    bloodGroup: "O+",
    birthDate: "2003-2-1",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Summer 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/tawsifislam65",
    LinkedIn: "https://www.linkedin.com/in/tawsif-islam-chowdhury-647a00238",
    Github: "https://github.com/phenomenalone1",
  },
  {
    name: "MD. JAHIRUL ISLAM ZISHAN",
    studentId: "21301474",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Creative",
    personalEmail: "bjzishan17@gmail.com",
    gSuiteEmail: "jahirul.islam.zishan@g.bracu.ac.bd",
    contactNumber: "01518681451",
    emergencyContact: "01716053933",
    bloodGroup: "A+",
    birthDate: "2000-11-17",
    gender: "Male",
    joinedBracu: "Summer 2021",
    joinedBucc: "Fall 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/its.bj.zishan",
    LinkedIn: "https://www.linkedin.com/in/md-jahirul-islam-zishan-085393213/",
    Github: "https://github.com/BjZishan",
  },
  {
    name: "Ishrak Hamim Mahi",
    studentId: "22101792",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Research and Development",
    personalEmail: "hameem.ishrak@gmail.com",
    gSuiteEmail: "ishrak.hamim.mahi@g.bracu.ac.bd",
    contactNumber: "01756555431",
    emergencyContact: "01712121817",
    bloodGroup: "O+",
    birthDate: "2002-1-6",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://m.facebook.com/profile.php?id=100077641630824",
    LinkedIn: "https://www.linkedin.com/in/ishrak-hamim-mahi-74a744246/",
    Github: "https://github.com/IshrakHamim",
  },
  {
    name: "Pritom Mondal",
    studentId: "22301184",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Creative",
    personalEmail: "pritommondal05@gmail.com",
    gSuiteEmail: "pritom.mondal@g.bracu.ac.bd",
    contactNumber: "01791634186",
    emergencyContact: "01741164794",
    bloodGroup: "O+",
    birthDate: "2002-5-25",
    gender: "Male",
    joinedBracu: "Summer 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/pritommondal.05",
    LinkedIn: "https://www.linkedin.com/in/pritommondal/",
    Github: "https://github.com/PritomMondal05",
  },
  {
    name: "Chandrima Roy Chowdhury",
    studentId: "22101246",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "chowdhurychandrimaroy@gmail.com",
    gSuiteEmail: "chandrima.roy.chowdhury@g.bracu.ac.bd",
    contactNumber: "01766616500",
    emergencyContact: "01533035632",
    bloodGroup: "B+",
    birthDate: "2002-8-30",
    gender: "Female",
    joinedBracu: "Spring 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/profile.php?id=100075932023400",
    LinkedIn: "https://www.linkedin.com/in/chandrima-roy-chowdhury-328baa24b",
    Github: "https://github.com/ChandrimaRoyChy",
  },
  {
    name: "Hamza Bin Islam",
    studentId: "22299280",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Finance",
    personalEmail: "hbizahin@gmail.com",
    gSuiteEmail: "hamza.bin.islam@g.bracu.ac.bd",
    contactNumber: "01841081323",
    emergencyContact: "01576696563",
    bloodGroup: "O+",
    birthDate: "2004-1-1",
    gender: "Male",
    joinedBracu: "Fall 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Spring 2023",
    Facebook: "https://www.facebook.com/hbi.zahin",
    LinkedIn: "www.linkedin.com/in/hbi-zahin-035907214",
    Github: "https://github.com/hbizahin",
  },
  {
    name: "Amina Zannat Nurhan",
    studentId: "23241099",
    departmentBracu: "CS",
    designation: "Senior Executive",
    buccDepartment: "Communications and Marketing",
    personalEmail: "aminajannat721@gmail.com",
    gSuiteEmail: "Amina.zannat.nurhan@g.bracu.ac.bd",
    contactNumber: "01979046735",
    emergencyContact: "01979046735",
    bloodGroup: "O+",
    birthDate: "2001-7-10",
    gender: "Female",
    joinedBracu: "Fall 2021",
    joinedBucc: "Fall 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/nurhan.zakir.9",
    LinkedIn: "https://www.linkedin.com/in/amina-zannat-2b501617b",
    Github: null,
  },
  {
    name: "Mubassir Rahman",
    studentId: "22301398",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "mubassirrahman25@gmail.com",
    gSuiteEmail: "mubassir.rahman@g.bracu.ac.bd",
    contactNumber: "01958462843",
    emergencyContact: "01719614975",
    bloodGroup: "B+",
    birthDate: "2024-1-15",
    gender: "Male",
    joinedBracu: "Summer 2022",
    joinedBucc: "Summer 2023",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/mrmubassir.rahman",
    LinkedIn: "https://www.linkedin.com/in/mubassir-rahman-370210293",
    Github: "https://github.com/Mubassir-no-Oxygen",
  },
  {
    name: "Rafiad Zaman Khan",
    studentId: "22101278",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "rafiadzamankhan512@gmail.com",
    gSuiteEmail: "rafiad.zaman.khan@g.bracu.ac.bd",
    contactNumber: "01771138016",
    emergencyContact: "01712784272",
    bloodGroup: "A+",
    birthDate: "2002-1-5",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/rafiad.zaman.khan",
    LinkedIn: "https://www.linkedin.com/in/rafiad-zaman-khan-5a00b6244",
    Github: "https://github.com/rafiadzamankhan",
  },
  {
    name: "Abdullah Shamsul Arefin",
    studentId: "24341289",
    departmentBracu: "CS",
    designation: "Senior Executive",
    buccDepartment: "Research and Development",
    personalEmail: "abdullah.shamsul.arefin@g.bracu.ac.bd",
    gSuiteEmail: "abdullah.shamsul.arefin@g.bracu.ac.bd",
    contactNumber: "01710835690",
    emergencyContact: "01538428678",
    bloodGroup: "O+",
    birthDate: "2001-11-13",
    gender: "Male",
    joinedBracu: "Fall 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/profile.php?id=100081302546777",
    LinkedIn: "linkedin.com/in/abdullah-shamsul-arefin-1054452b2",
    Github: "https://github.com/Abdullah-Arefin",
  },
  {
    name: "Tahsina Rahman",
    studentId: "22201417",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "tahsinarahman0007@gmail.com",
    gSuiteEmail: "tahsina.rahman1@g.bracu.ac.bd",
    contactNumber: "01721614277",
    emergencyContact: "01533349200",
    bloodGroup: "B+",
    birthDate: "2002-11-11",
    gender: "Female",
    joinedBracu: "Fall 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/tahsina.moon.77",
    LinkedIn: null,
    Github: "https://github.com/Tahsina417",
  },
  {
    name: "ISTIAK ZAMAN SHUVO",
    studentId: "24141262",
    departmentBracu: "CS",
    designation: "Senior Executive",
    buccDepartment: "Human Resources",
    personalEmail: "istiak2027@gmail.com",
    gSuiteEmail: "istiak.zaman.shuvo@g.bracu.ac.bd",
    contactNumber: "01756020067",
    emergencyContact: "01756020067",
    bloodGroup: "AB+",
    birthDate: "2001-6-13",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/istiak.z.shuvo",
    LinkedIn: "https://www.linkedin.com/in/istiak-zaman-shuvo",
    Github: "https://github.com/istiak1000",
  },
  {
    name: "Samirah Alom Sarah",
    studentId: "24141110",
    departmentBracu: "CS",
    designation: "Senior Executive",
    buccDepartment: "Finance",
    personalEmail: "sarah.alom3009@gmail.com",
    gSuiteEmail: "samirah.alom.sarah@g.bracu.ac.bd",
    contactNumber: "01786405120",
    emergencyContact: "01786405121",
    bloodGroup: "O+",
    birthDate: "2000-4-13",
    gender: "Female",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2022",
    lastPromotion: "Summer 2023",
    Facebook: "https://www.facebook.com/samirahalom.sarah",
    LinkedIn: "https://www.linkedin.com/in/samirah-alom-sarah-79357a2b6",
    Github: null,
  },
  {
    name: "Sumaya Hasan Prokrity",
    studentId: "21201455",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "sumayahasanprokrity@gmail.com",
    gSuiteEmail: "sumaya.hasan.prokrity@g.bracu.ac.bd",
    contactNumber: "01639660001",
    emergencyContact: "01972825144",
    bloodGroup: "O+",
    birthDate: "2001-11-25",
    gender: "Female",
    joinedBracu: "Fall 2021",
    joinedBucc: "Spring 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/pro.757krity",
    LinkedIn: null,
    Github: "https://github.com/shprokrity",
  },
  {
    name: "Sayani Das",
    studentId: "22101754",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Creative",
    personalEmail: "sayanidashcc@gmail.com",
    gSuiteEmail: "sayani.das@g.bracu.ac.bd",
    contactNumber: "01307758504",
    emergencyContact: "01931337930",
    bloodGroup: "O+",
    birthDate: "2000-10-21",
    gender: "Female",
    joinedBracu: "Spring 2020",
    joinedBucc: "Fall 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/profile.php?id=100024560652907",
    LinkedIn: null,
    Github: null,
  },
  {
    name: "Suchitra barua",
    studentId: "22101617",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "suchitrabarua6@gmail.com",
    gSuiteEmail: "suchitra.barua@g.bracu.ac.bd",
    contactNumber: "01626905982",
    emergencyContact: "01625329390",
    bloodGroup: "O+",
    birthDate: "2001-9-17",
    gender: "Female",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2022",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/profile.php?id=100009929708249",
    LinkedIn: null,
    Github: null,
  },
  {
    name: "Khandoker Nazmul Islam",
    studentId: "22101044",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "nazmulislam098.raj@gmail.com",
    gSuiteEmail: "khandoker.nazmul.islam@g.bracu.ac.bd",
    contactNumber: "01752011225",
    emergencyContact: "01711972182",
    bloodGroup: "B+",
    birthDate: "2003-9-10",
    gender: "Male",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/knib.07",
    LinkedIn: null,
    Github: null,
  },
  {
    name: "Tasin Ahsan Rhidy",
    studentId: "22101720",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Communications and Marketing",
    personalEmail: "rhidytasinahsan@gmail.com",
    gSuiteEmail: "tasin.ahsan.rhidy@g.bracu.ac.bd",
    contactNumber: "01919011773",
    emergencyContact: "01919011773",
    bloodGroup: "O+",
    birthDate: "2002-1-11",
    gender: "Female",
    joinedBracu: "Spring 2022",
    joinedBucc: "Spring 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/profile.php?id=100076366343780",
    LinkedIn: "https://www.linkedin.com/in/tasin-ahsan-rhidy-197853233",
    Github: null,
  },
  {
    name: "NIAMUL HASAN CHOWDHURY",
    studentId: "22301117",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "tanjil07isc@gmail.com",
    gSuiteEmail: "niamul.hasan.chowdhury@g.bracu.ac.bd",
    contactNumber: "01521721290",
    emergencyContact: "01790536839",
    bloodGroup: "O+",
    birthDate: "2003-12-12",
    gender: "Male",
    joinedBracu: "Summer 2022",
    joinedBucc: "Summer 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/nhc.tanjil",
    LinkedIn: null,
    Github: "https://github.com/nhctanjil",
  },
  {
    name: "ANINDITA DUTTA",
    studentId: "22101031",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Finance",
    personalEmail: "anindita.dutta@g.bracu.ac.bd",
    gSuiteEmail: "anindita.dutta@g.bracu.ac.bd",
    contactNumber: "01794812124",
    emergencyContact: "01813174218",
    bloodGroup: "AB+",
    birthDate: "2001-5-7",
    gender: "Female",
    joinedBracu: "Spring 2022",
    joinedBucc: "Summer 2022",
    lastPromotion: "Fall 2023",
    Facebook: "https://www.facebook.com/profile.php?id=100068967185074",
    LinkedIn: "https://www.linkedin.com/in/anindita-dutta-24337b25a",
    Github: "https://github.com/Anindita-Dutta-Ani",
  },
  {
    name: "Taiaba Jaman Shuchona",
    studentId: "22301250",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Finance",
    personalEmail: "tjshuchona14@gmail.com",
    gSuiteEmail: "taiaba.jaman.shuchona@g.bracu.ac.bd",
    contactNumber: "01313983232",
    emergencyContact: "01725121661",
    bloodGroup: "A+",
    birthDate: "2002-5-1",
    gender: "Female",
    joinedBracu: "Summer 2022",
    joinedBucc: "Spring 2023",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/taiabajaman.shuchona.1",
    LinkedIn: "https://www.linkedin.com/in/taiaba-jaman-shuchona-a3b4922a9",
    Github: null,
  },
  {
    name: "Mehjabin Mostare Momo",
    studentId: "22201034",
    departmentBracu: "CSE",
    designation: "Senior Executive",
    buccDepartment: "Event Management",
    personalEmail: "mehjabinmushtari1@gmail.com",
    gSuiteEmail: "mehjabin.mostare.momo@g.bracu.ac.bd",
    contactNumber: "01860900459",
    emergencyContact: "01716493622",
    bloodGroup: "B+",
    birthDate: "2003-8-23",
    gender: "Female",
    joinedBracu: "Fall 2022",
    joinedBucc: "Fall 2022",
    lastPromotion: "Spring 2024",
    Facebook: "https://www.facebook.com/profile.php?id=100054431475117",
    LinkedIn: "https://www.linkedin.com/in/mehjabin-momo-40709b2b1",
    Github: "https://github.com/Mehjabin12",
  },
];

export default BUCCSEs;
