const skills = [
  { label: "Android Development", value: "Android Development" },
  { label: "iOS Development", value: "iOS Development" },
  { label: "Web Development", value: "Android Development" },
  { label: "Frontend Development", value: "Frontend Development" },
  { label: "Backend Development", value: "Backend Development" },
  { label: "Full Stack Development", value: "Full Stack Development" },
  { label: "Game Development", value: "Game Development" },
  { label: "UI/UX Design", value: "UI/UX Design" },
  { label: "Graphic Design", value: "Graphic Design" },
  { label: "Product Management", value: "Product Management" },
  { label: "Project Management", value: "Project Management" },
  { label: "Quality Assurance", value: "Quality Assurance" },
  { label: "DevOps", value: "DevOps" },
  { label: "Data Science", value: "Data Science" },
  { label: "Machine Learning", value: "Machine Learning" },
  { label: "Artificial Intelligence", value: "Artificial Intelligence" },
  { label: "Cybersecurity", value: "Cybersecurity" },
  { label: "Blockchain", value: "Blockchain" },
  { label: "IoT", value: "IoT" },
  { label: "AR/VR", value: "AR/VR" },
  { label: "Cloud Computing", value: "Cloud Computing" },
  { label: "Robotics", value: "Robotics" },
  { label: "JavaScript", value: "JavaScript" },
  { label: "TypeScript", value: "TypeScript" },
  { label: "React", value: "React" },
  { label: "Angular", value: "Angular" },
  { label: "Vue", value: "Vue" },
  { label: "Node.js", value: "Node.js" },
  { label: "Express", value: "Express" },
  { label: "NestJS", value: "NestJS" },
  { label: "Python", value: "Python" },
  { label: "Django", value: "Django" },
  { label: "Flask", value: "Flask" },
  { label: "Ruby", value: "Ruby" },
  { label: "Java", value: "Java" },
  { label: "Spring", value: "Spring" },
  { label: "Kotlin", value: "Kotlin" },
  { label: "Swift", value: "Swift" },
  { label: "Flutter", value: "Flutter" },
  { label: "Dart", value: "Dart" },
  { label: "C#", value: "C#" },
  { label: "Unity", value: "Unity" },
  { label: "C++", value: "C++" },
  { label: "PHP", value: "PHP" },
  { label: "Laravel", value: "Laravel" },
  { label: "Ruby on Rails", value: "Ruby on Rails" },
  { label: "HTML", value: "HTML" },
  { label: "CSS", value: "CSS" },
  { label: "Sass", value: "Sass" },
  { label: "Less", value: "Less" },
  { label: "Bootstrap", value: "Bootstrap" },
  { label: "Tailwind CSS", value: "Tailwind CSS" },
  { label: "Material-UI", value: "Material-UI" },
  { label: "Ant Design", value: "Ant Design" },
  { label: "GraphQL", value: "GraphQL" },
  { label: "Apollo", value: "Apollo" },
  { label: "REST API", value: "REST API" },
  { label: "Firebase", value: "Firebase" },
  { label: "MongoDB", value: "MongoDB" },
  { label: "MySQL", value: "MySQL" },
  { label: "PostgreSQL", value: "PostgreSQL" },
  { label: "SQLite", value: "SQLite" },
  { label: "Docker", value: "Docker" },
  { label: "Kubernetes", value: "Kubernetes" },
  { label: "Git", value: "Git" },
  { label: "AWS", value: "AWS" },
  { label: "Azure", value: "Azure" },
  { label: "Google Cloud", value: "Google Cloud" },
  { label: "Heroku", value: "Heroku" },
  { label: "Netlify", value: "Netlify" },
  { label: "Vercel", value: "Vercel" },
  { label: "DigitalOcean", value: "DigitalOcean" },
  { label: "Socket.IO", value: "Socket.IO" },
  { label: "WebSockets", value: "WebSockets" },
  { label: "WebRTC", value: "WebRTC" },
];

export default skills;
