import AnonMale from "./board-members-images/anonMale.png";
import AnnonFemale from "./board-members-images/anonFemale.png";

const ExecutiveBody2020 = [
  {
    fullName: "Humayun Ahmed",
    nickName: "Humayun",
    department: "Governing Body",
    designation: "President",
    image: AnonMale,
  },
  {
    fullName: "Nazmus Saquib",
    nickName: "Saquib",
    department: "Governing Body",
    designation: "Vice President",
    image: AnonMale,
  },
  {
    fullName: "Mushfiqul Islam Chowdhury",
    nickName: "Mushfiqul",
    department: "Governing Body",
    designation: "General Secretary",
    image: AnonMale,
  },
  {
    fullName: "Faheem Ahmed",
    nickName: "Faheem",
    department: "Creative",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Tahseen Tayeb Kabir",
    nickName: "Tahseen",
    department: "Creative",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "MD. AL-JUNAED ISLAM",
    nickName: "Junaed",
    department: "Creative",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Touhidul Islam Chayan",
    nickName: "Chayan",
    department: "Creative",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Samia Salam Suzana",
    nickName: "Suzana",
    department: "Creative",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
  {
    fullName: "Fahd Zakwan",
    nickName: "Fahd",
    department: "Event Management",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Nayem Ul Islam",
    nickName: "Nayem",
    department: "Event Management",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Sazia Afroz",
    nickName: "Sazia",
    department: "Event Management",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
  {
    fullName: "Anita Islam",
    nickName: "Anita",
    department: "Event Management",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
  {
    fullName: "Fatema Islam Meem",
    nickName: "Meem",
    department: "Event Management",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
  {
    fullName: "M. Samiur Rahman Susmoy",
    nickName: "Susmoy",
    department: "Finance",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Shamiul Islam Shuvo",
    nickName: "Shuvo",
    department: "Finance",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Sunanda Biswas",
    nickName: "Sunanda",
    department: "Finance",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
  {
    fullName: "Mubasshira Mizan",
    nickName: "Mizan",
    department: "Finance",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
  {
    fullName: "Sudip Kumar Sengupta",
    nickName: "Sudip",
    department: "Human Resources",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Serazam Munira Khondaker",
    nickName: "Serazam",
    department: "Human Resources",
    designation: "Director",
    image: AnnonFemale,
  },
  {
    fullName: "A.E.M Ridwan",
    nickName: "Ridwan",
    department: "Human Resources",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Fatema Ahsan",
    nickName: "Fatema",
    department: "Human Resources",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
  {
    fullName: "Asif Shariar Likhon",
    nickName: "Likhon",
    department: "Marketing",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Saiham Rahman",
    nickName: "Saiham",
    department: "Marketing",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Mekhala Mariam Mary",
    nickName: "Mary",
    department: "Marketing",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
  {
    fullName: "Tiash Roy",
    nickName: "Tiash",
    department: "Press Release and Publication",
    designation: "Director",
    image: AnonMale,
  },
  {
    fullName: "Niloy Deb Roy Mishu",
    nickName: "Mishu",
    department: "Press Release and Publication",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Shihab Sharar",
    nickName: "Shihab",
    department: "Press Release and Publication",
    designation: "Assistant Director",
    image: AnonMale,
  },
  {
    fullName: "Farisha Tabassum",
    nickName: "Farisha",
    department: "Press Release and Publication",
    designation: "Assistant Director",
    image: AnnonFemale,
  },
];

export default ExecutiveBody2020;
